"""Provider boundary. Adapters normalize their protocol into runtime events.

The orchestrator owns request identity, execution-policy inheritance, containment,
terminal-result validation and publication. Providers own executable selection,
capabilities, native policy translation, launch preparation and control semantics.
Historical state keys remain persistence compatibility details inside providers.
"""
from typing import Protocol, Any, Callable
from dataclasses import dataclass
from pathlib import Path


class ProviderAdapter(Protocol):
    def executable(self, args: Any, session: dict | None = None) -> str: ...
    def session_fields(self, executable: str, capabilities: dict | None = None) -> dict: ...
    def persisted_fields(self, session: dict) -> dict: ...
    def inspect_capabilities(self, executable: str, **kwargs: Any) -> dict: ...
    def validate(self, session: dict, **kwargs: Any) -> None: ...
    def validate_execution(self, session: dict, goal_action: str | None = None) -> None: ...
    def discover_policy(self, args: Any, working_root: str, **kwargs: Any) -> dict: ...
    def check(self, session: dict, policy: dict, working_directory: Path,
              run_directory: Path, request_path: Path) -> dict: ...
    def prepare(self, session: dict, state: dict, request: bytes) -> None: ...
    def uses_prompt_parts(self, session: dict) -> bool: ...
    def fatal_error_events(self, session: dict) -> bool: ...
    def build_command(self, session: dict, state: dict, session_id: str | None,
                      *, prompt_parts: bool = False) -> list[str]: ...
    def before_stop(self, state_path: Path, state: dict, *, cancel: bool = False) -> None: ...
    def goal_command(self, runtime: Any, args: Any, root: Path, session: dict) -> int: ...


@dataclass(frozen=True)
class GoalServices:
    """Bounded orchestration callbacks available to provider control commands."""
    emit: Callable
    agent_directory: Callable
    file_lock: Callable
    iter_run_states: Callable
    update_json: Callable
    parse_args: Callable
    submit: Callable
    active_states: frozenset[str]
    schema_version: str
    # Stop an active run (agent_id, run_id) without emitting a response; providers without
    # live Goal controls use it to pause or clear a Goal mid-run.
    stop_run: Callable | None = None
